### ISSUE TITLE
Map shortcut still active while typing savegame name and in any other menu

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#113]
Build 49

While typing the name for the savegame, the Voogle Maps shortcut is still active, so every time I type "m" it will toggle the map display.

https://user-images.githubusercontent.com/17579552/120252504-fd88ba80-c284-11eb-9896-2f5efdf4affc.mp4

**Comment by adameg2305** [comment]
Same For Bizman, but in any menu if you press "M" it will open the menu in the background

**Comment by jhovgaard** [comment]
Fixed in build 55

**Comment by Gerwanese** [comment]
The second part (see comment by @adameg2305) is still not fixed - in phone apps (for example BizMan), the M shortcut still works. I can even click some of the Voogle Maps controls.
Besides, Ctrl+M now doesn't quit the game anymore but opens Voogle Maps as well - is it by purpose that modifiers have no effect in this case?


https://user-images.githubusercontent.com/17579552/121818438-788ba100-cc87-11eb-9c1d-705981d4621b.mp4

**Comment by jhovgaard** [comment]
Fixed in build 60

**Comment by Gerwanese** [comment]
Very sorry to open this again - I know you have fixed it to Voogle Maps opening when M is pressed in the phone apps.
In Build 66 however, pressing M will just close the phone apps. Maybe a side effect of some other fix?

**Comment by jhovgaard** [comment]
Nothing to be sorry about! :D Was caused by another bug interrupting the action.

Fixed in build 67
