### ISSUE TITLE
Can't pick up hand truck parked right after leaving store and can't re-enter store

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#145]
Build 51

If I park the hand truck right after leaving a store (without moving at all) it's impossible to pick up the hand truck again.
Also it's not possible to enter the store again.
In both cases the player will just keep running trying to get in between door and hand truck.

Workaround: Remove anything from the hand truck and enter another building. After leaving the other building, the hand truck will be gone.

https://user-images.githubusercontent.com/17579552/120905311-920e6680-c651-11eb-8280-7247f0066cb2.mp4

**Comment by jhovgaard** [comment]
Fixed in some build.

**Comment by Gerwanese** [comment]
Build 54
Problem still exists, here in 10 Fourth Avenue. Can't pick up hand truck and also can't enter the building.


https://user-images.githubusercontent.com/17579552/121816483-301ab600-cc7c-11eb-85a9-509a711ca374.mp4

**Comment by Gerwanese** [comment]
Additionally to my previous comment, if I park a hand truck right after entering a shop, I can't pick it up anymore and also can't leave the shop.
This is a much more serious issue as I can't work around it by entering another building - I'm effectively stuck and can only quit the game.
Unfortunately it's still there after saving and reloading, so I would consider this a game breaking bug (at least savegame breaking bug).

https://user-images.githubusercontent.com/17579552/121817054-5f7ef200-cc7f-11eb-86b9-abca1bfdc7bd.mp4

**Comment by jhovgaard** [comment]
Fixed in build 66.

I have added navigation obstacles to all building colliders. This is quite a large change and might introduce other navigation issues, especially related to entering buildings.

**Comment by Gerwanese** [comment]
The hand truck can still block a building entrance, but it's possible to pick it up so I consider it fixed (realistically, you would also remove the hand truck before getting in, so that's just right).

**Comment by tomvbj** [comment]
[BUILD 71 Handtruck BUG.txt](https://github.com/hovgaardgames/bigambitions-public/files/6777403/BUILD.71.Handtruck.BUG.txt)

**Comment by Gerwanese** [comment]
Bug still occurs in @tomvbj 's save in build 75.

**Comment by jhovgaard** [comment]
@tomvbj The handtruck was placed at that specific spot in an earlier build right? It shouldn't be possible to park it at the spot in the current version.
