### ISSUE TITLE
Not a single customer getting into gift shop anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#257]
Build 71

Since build 71, not a single customer is entering my gift shop anymore. Shop is opened, shelves all filled up, I got a VERY friendly cashier but people still refuse to come. Feels like a pandemic in NY.

[Build71.txt](https://github.com/hovgaardgames/bigambitions-public/files/6750881/Build71.txt)

https://user-images.githubusercontent.com/17579552/124191728-82553700-dac4-11eb-9457-a6f39d8703d4.mp4

**Comment by jhovgaard** [comment]
Fixed in build 74

**Comment by Gerwanese** [comment]
Still happened in build 75.
It happened after all stock was sold out in the shop and I refilled some time later.
It also happend only while I had an employee working there. As soon as I start working myself, customers start coming again.

In the savegame you're standing in the restaurant but the affected business is my gift shop. :)
You can see in BizMan that I didn't have any sales recently.

[Build75-NewRestaurant.txt](https://github.com/hovgaardgames/bigambitions-public/files/6778858/Build75-NewRestaurant.txt)

**Comment by jhovgaard** [comment]
It's "can't reproduce" day :D 

Might have been fixed by something else. Build 76. 
![image](https://user-images.githubusercontent.com/1388347/124932125-195d4a00-e003-11eb-85ac-f946270fb320.png)

**Comment by jhovgaard** [comment]
![image](https://user-images.githubusercontent.com/1388347/124933062-df407800-e003-11eb-87cd-5197037cbf13.png)
I got customers at Gifty's after 13 o'clock. Maybe fixed by something else? Build 76

**Comment by Gerwanese** [comment]
Have to reopen again, but now with some new information:

If you load the save and let it run on double speed the whole day (staying inside the fast food restaurant), the restaurant will make good money but the gift shop will sell nothing.
If you instead head home and sleep the whole day, both the gift shop and the restaurant will sell nothing.
Obviously there are no customers if you're not in the shop yourself, even though there are employees.
Additionally, if I enter Gifty's sometime in the afternoon (for example around 4pm), a large group of people will immediately come in, just as if they waited for me to be there first.

[Build75-NobodyLikesGiftys-SoSad.txt](https://github.com/hovgaardgames/bigambitions-public/files/6795730/Build75-NobodyLikesGiftys-SoSad.txt)

**Comment by jhovgaard** [comment]
Alright, I couldn't reproduce, but I found out that the chart wasn't updating after showing for the first time. I'm think that's what caused the confusion. Fixed in build 77

**Comment by Gerwanese** [comment]
Reopening with investigation results, based on a newly started savegame in build 78:

Base calculation - Sunday 00:18:

**Asset**        |  **Amount**
----------|--------------
Cash        | $2491
Apartment rent | -$64
Business rent | -$114
Daily wage employee | -$210
 ./.  |    
Income without sales | -$388
Cash afterwards | $2103

**Stock**        |  **Amount**
----------|--------------
CheapGift | 21
PaperBag | 826
Items sold last 7 days | 199
Gross profit margin | $2068
Product range | 77%
Pricing | 100%


After one day sleeping - Monday 00:24:

**Asset**        |  **Amount**
----------|--------------
Cash        | $2104
Note the $1 difference to the expectation - the same happened in my previous savegame, I always have $1 more than expected, probably a rounding issue somewhere.

**Stock**        |  **Amount**
----------|--------------
CheapGift | 21
PaperBag | 826
Items sold last 7 days | **261**
Gross profit margin | $2068
Product range | **0%**
Pricing | **0%**

As you can see, I have not sold a single item. Product range and pricing go down to 0%. Bank account reduces accordingly.
Items sold last 7 days for some reason goes up by 62 (can't be the value of the previous day as that was only 60).

[Build78-NobodyLikesNYGifts.txt](https://github.com/hovgaardgames/bigambitions-public/files/6818887/Build78-NobodyLikesNYGifts.txt)


https://user-images.githubusercontent.com/17579552/125691235-38053c48-d954-4ed8-81c4-9b9291ad7f94.mp4

**Comment by jhovgaard** [comment]
What a mess! First this was caused by the chained errors from recruitment campaigns. Secondly, it was also grabbing wrong shelves after the rewrite.

Fixed in build 79.
