### ISSUE TITLE
Most people on the street can't be interviewed anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#284]
Build 75

After starting a new game, I can't interview most of the people on the street anymore. The interview overlay only appears for about 1 out of 10 people (with only 2 people having been interviewed before at all, the third one during the video).

[Build75-NoInterviews.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773052/Build75-NoInterviews.txt)

https://user-images.githubusercontent.com/17579552/124672818-feca8a00-deb7-11eb-8076-efbdeed59d9c.mp4

**Comment by jhovgaard** [comment]
Fixed in build 76

**Comment by Gerwanese** [comment]
Unfortunately still happens in a brand new game.
I also got stuck again during one interview and couldn't move anymore (visible in the end of the video), so I will also reopen the bug regarding this.

https://user-images.githubusercontent.com/17579552/125173337-160ebd80-e1bf-11eb-9620-a5a2d87a456a.mp4

**Comment by jhovgaard** [comment]
Fixed in build 78, hopefully!
