### ISSUE TITLE
Vehicle hitboxes too big

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#37]
https://i.adameg.net/xi8iv0hh.png
The van's hitboxes are a bit too big.

**Comment by adameg2305** [comment]
Hitboxes for the cars aswell ^

**Comment by Gerwanese** [comment]
Confirmed, at scale I'd guess it's about 50cm gap between vehicles.

**Comment by jhovgaard** [comment]
Fixed too wide colliders for all vehicles. Build 49

**Comment by Gerwanese** [comment]
Still an issue at least with some cars. From the side seems to be good but the corners are... "edgy". ;)
Grey car in first video, blue van in second.

https://user-images.githubusercontent.com/17579552/120248989-a3362c80-c279-11eb-9fec-c8fffde888d4.mp4


https://user-images.githubusercontent.com/17579552/120248993-a6c9b380-c279-11eb-853a-d32936afaec6.mp4

**Comment by jhovgaard** [comment]
We'll have to switch to mesh colliders to avoid this issue. For now it would be too expensive compared to the gains. Closing now, but can be re-opened if people continue to report it.
