### ISSUE TITLE
Bank allows unlimited loans

### ISSUE THREAD

**Issue by niels-hubs** [hovgaardgames/bigambitions-public#378]
Hi,

When you sell your business and apartment in the third fase (when you need to complete business fund.) you can go to the bank and constantly take out a loan of 25.000$ infinitely, without paying it back.

**Comment by Gerwanese** [comment]
It's not fixed to 25k. The bank loan depends on your recent income, so the more you sold the more you get. So actually there are to bugs:
1. Selling your businesses and terminating the contracts counts as "income", raising the allowance
2. The allowed loan amount can be borrowed unlimited times.

[Build106-SellAllForANewStart.txt](https://github.com/hovgaardgames/bigambitions-public/files/6909823/Build106-SellAllForANewStart.txt)

https://user-images.githubusercontent.com/17579552/127706836-650f5ebb-d66e-47d3-b5f5-6b5e605e9783.mp4

**Comment by jhovgaard** [comment]
Fixed in build 131

**Comment by Gerwanese** [comment]
Bug is back at build 153.

[Build153-EndlessMoney.txt](https://github.com/hovgaardgames/bigambitions-public/files/6994531/Build153-EndlessMoney.txt)

https://user-images.githubusercontent.com/17579552/129611499-cd3fd227-ab70-46ce-9620-c349ad397d8b.mp4

**Comment by jhovgaard** [comment]
Loans wasn't included in daily income-based approval. Fixed in build 163
