### ISSUE TITLE
Parts of UI missing on ultra wide screens

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#388]
Build 123

Players using ultrawide screens / resolutions currently can't play the game as parts of the UI with important controls are missing.

https://community.bigambitionsgame.com/t/screen-resolution-renting-the-first-apartment/282

![grafik](https://user-images.githubusercontent.com/17579552/127737309-a72b8698-eec6-409e-8dcb-86810738c147.png)

**Comment by jhovgaard** [comment]
Fixed in build 130

**Comment by Gerwanese** [comment]
Depends on what you call fixed... apps broken now on non-widescreens. :)
Just start a new game and open any phone app. Everything below the blue header line will extend outside the screen.

![grafik](https://user-images.githubusercontent.com/17579552/127748356-d3244eb6-df71-4687-b24f-729e3f5e8294.png)

**Comment by Gerwanese** [comment]
Additionally to my previous comment (UI broken for non-wide displays), there's also still an issue with the initial text on ultrawide screens:

> The top text is still partially hidden though, when you start a new game, but perhaps that is a different reason.
> ![grafik](https://user-images.githubusercontent.com/17579552/127749507-19a03d56-f773-4232-9f63-8d6815e67d92.png)

**Comment by jhovgaard** [comment]
Fixed in build 132
