### ISSUE TITLE
Gift shop: Sodacans and Paperbags not reducing

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#473]
Build 172

When running a gift shop, sodacans and paperbags don't reduce, while gifts reduce normally.
In EconoView you can see that sodacans are sold.
After a while, quantities will reduce very slowly. It seems as if every customer will just get 0.01 of each item.

[Build172-GiftshopNoSodacanNoPaperbag.txt](https://github.com/hovgaardgames/bigambitions-public/files/7062929/Build172-GiftshopNoSodacanNoPaperbag.txt)

https://user-images.githubusercontent.com/17579552/131042291-cf4eebb3-2a72-426b-83ac-9158b12755c2.mp4

**Comment by jhovgaard** [comment]
Fixed in build 173

**Comment by Gerwanese** [comment]
Not completely fixed:
Sodacans reducing, but with 15 Sodacans and 43 CheapGifts sold I'd expect more than 3 Paperbags being used.

[Build175-PaperbagsNotReducingProperly.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071412/Build175-PaperbagsNotReducingProperly.txt)

![grafik](https://user-images.githubusercontent.com/17579552/131229678-08464dd7-64ed-45b6-9999-005abead5f81.png)

**Comment by jhovgaard** [comment]
Fixed in build 177
