### ISSUE TITLE
Possible to accidentally eat while placing a (filled) fridge

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#520]
Build 181

If you try to place a filled fridge, the "Eat Freshfood" button is still shown and it can happen that you accidentally eat.

[Build181-EatWhileHoldingFridge.txt](https://github.com/hovgaardgames/bigambitions-public/files/7085522/Build181-EatWhileHoldingFridge.txt)

https://user-images.githubusercontent.com/17579552/131543817-d0114e3e-01ef-4c41-8f7f-b899a2c3b7ab.mp4

**Comment by jokoho48** [comment]
Fixed in Build 182

**Comment by Gerwanese** [comment]
It's fixed when right-clicking and placing it. But if I "grab" it and then place the box again, it's still the same issue in build 182.
