### ISSUE TITLE
Cars stop when in front of them but drive on when running against them

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions-public#56]
Alpha 3 - Build 12
https://i.adameg.net/EtBZAi.mp4

Cars stop when you get within a certain distance of them, however, when you run towards them they start driving and become faster than what they normally are.

**Comment by jhovgaard** [comment]
Internal note: Probably gap between box collider and front sensor

**Comment by jhovgaard** [comment]
Fixed in build 49

**Comment by Gerwanese** [comment]
Still happening, although smarter person movement makes it more difficult to reproduce. ;)
I think it's not a big problem though, so you might decide to keep it as it is right now.

https://user-images.githubusercontent.com/17579552/120247755-e4780d80-c274-11eb-89bd-3669373d8e10.mp4

**Comment by jhovgaard** [comment]
Double fixed in build 51
