### ISSUE TITLE
Paper bag becomes Box on hand truck

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions-public#83]
Build: 49

When picking up the hand truck while holding a paper bag in hands, the paper bag will turn into a box.

https://user-images.githubusercontent.com/17579552/120241782-c655e180-c263-11eb-9964-7f7053243a69.mp4

**Comment by jhovgaard** [comment]
This is by design. Alternatively, we should completely disable the option to carry paperbags on the handtruck. What do you think @Gerwanese @adameg2305?

**Comment by Gerwanese** [comment]
@jhovgaard I would completely disable the option. Hand trucks are for large items and boxes.
The player could carry a paper bag and the hand truck simultaneously, but I guess that would be too much animation work for just a very small benefit.

**Comment by jokoho48** [comment]
Fixed in Build 191

**Comment by Gerwanese** [comment]
Not fixed for me in build 208.
I had a hand truck with 2 boxes on it (parked) and a paper bag in my hands. When clicking on the hand truck, I will hold the hand truck and the paper bag will be the third box on the hand truck.

**Comment by jokoho48** [comment]
Fixed in Build 209 this time really hopefully in all places and conditions 😄
